using System;
using System.Collections.Generic;

namespace API_DCI_DIAGRAM_SVG.Models
{
    public partial class Do5Order
    {
        public int RunningId { get; set; }
        public string? RunningCode { get; set; }
        public string? DataYear { get; set; }
        public string? DataMonth { get; set; }
        public string? DataType { get; set; }
        public string? DoType { get; set; }
        public string? PoNbr { get; set; }
        public string? VdAddr { get; set; }
        public string? VdSort { get; set; }
        public string? ItemNumber { get; set; }
        public string? ItemUm { get; set; }
        public decimal? ItemWip { get; set; }
        public decimal? ItemStock { get; set; }
        public decimal? ItemDoBalance { get; set; }
        public string? OrderType { get; set; }
        public int? OrderLeadtime { get; set; }
        public decimal? SafetyQty { get; set; }
        public decimal? CurrentQoQty { get; set; }
        public decimal? FutureDoQty { get; set; }
        public decimal? ReqPlan { get; set; }
        public decimal? PackingStd { get; set; }
        public string? DefaultSupplier { get; set; }
        public decimal? SupplierRatio { get; set; }
        public DateTime? OrderDate { get; set; }
        public string? OrderTime { get; set; }
        public string? D01Code { get; set; }
        public string? D02Code { get; set; }
        public string? D03Code { get; set; }
        public string? D04Code { get; set; }
        public string? D05Code { get; set; }
        public string? D06Code { get; set; }
        public string? D07Code { get; set; }
        public string? D08Code { get; set; }
        public string? D09Code { get; set; }
        public string? D10Code { get; set; }
        public string? D11Code { get; set; }
        public string? D12Code { get; set; }
        public string? D13Code { get; set; }
        public string? D14Code { get; set; }
        public string? D15Code { get; set; }
        public string? D16Code { get; set; }
        public string? D17Code { get; set; }
        public string? D18Code { get; set; }
        public string? D19Code { get; set; }
        public string? D20Code { get; set; }
        public string? D21Code { get; set; }
        public string? D22Code { get; set; }
        public string? D23Code { get; set; }
        public string? D24Code { get; set; }
        public string? D25Code { get; set; }
        public string? D26Code { get; set; }
        public string? D27Code { get; set; }
        public string? D28Code { get; set; }
        public string? D29Code { get; set; }
        public string? D30Code { get; set; }
        public string? D31Code { get; set; }
        public decimal? D01Qty { get; set; }
        public decimal? D02Qty { get; set; }
        public decimal? D03Qty { get; set; }
        public decimal? D04Qty { get; set; }
        public decimal? D05Qty { get; set; }
        public decimal? D06Qty { get; set; }
        public decimal? D07Qty { get; set; }
        public decimal? D08Qty { get; set; }
        public decimal? D09Qty { get; set; }
        public decimal? D10Qty { get; set; }
        public decimal? D11Qty { get; set; }
        public decimal? D12Qty { get; set; }
        public decimal? D13Qty { get; set; }
        public decimal? D14Qty { get; set; }
        public decimal? D15Qty { get; set; }
        public decimal? D16Qty { get; set; }
        public decimal? D17Qty { get; set; }
        public decimal? D18Qty { get; set; }
        public decimal? D19Qty { get; set; }
        public decimal? D20Qty { get; set; }
        public decimal? D21Qty { get; set; }
        public decimal? D22Qty { get; set; }
        public decimal? D23Qty { get; set; }
        public decimal? D24Qty { get; set; }
        public decimal? D25Qty { get; set; }
        public decimal? D26Qty { get; set; }
        public decimal? D27Qty { get; set; }
        public decimal? D28Qty { get; set; }
        public decimal? D29Qty { get; set; }
        public decimal? D30Qty { get; set; }
        public decimal? D31Qty { get; set; }
        public decimal? TotalShort { get; set; }
        public string? Status { get; set; }
        public int? Revision { get; set; }
        public DateTime? CreateDate { get; set; }
        public string? CreateBy { get; set; }
        public DateTime? UpdateDate { get; set; }
        public string? UpdateBy { get; set; }
        public string? InputType { get; set; }
    }
}
