using System;
using System.Collections.Generic;

namespace API_DCI_DIAGRAM_SVG.Models
{
    public partial class PdAchievement
    {
        public int RecNbr { get; set; }
        public string? ProductionLine { get; set; }
        public string? ProductionLineName { get; set; }
        public string? Model { get; set; }
        public string? ModelCode { get; set; }
        public int? DataMonth { get; set; }
        public int? DataYear { get; set; }
        public int? AccumulateDiff { get; set; }
        public int? Day1DPlan { get; set; }
        public int? Day1DActual { get; set; }
        public int? Day1NPlan { get; set; }
        public int? Day1NActual { get; set; }
        public int? Day2DPlan { get; set; }
        public int? Day2DActual { get; set; }
        public int? Day2NPlan { get; set; }
        public int? Day2NActual { get; set; }
        public int? Day3DPlan { get; set; }
        public int? Day3DActual { get; set; }
        public int? Day3NPlan { get; set; }
        public int? Day3NActual { get; set; }
        public int? Day4DPlan { get; set; }
        public int? Day4DActual { get; set; }
        public int? Day4NPlan { get; set; }
        public int? Day4NActual { get; set; }
        public int? Day5DPlan { get; set; }
        public int? Day5DActual { get; set; }
        public int? Day5NPlan { get; set; }
        public int? Day5NActual { get; set; }
        public int? Day6DPlan { get; set; }
        public int? Day6DActual { get; set; }
        public int? Day6NPlan { get; set; }
        public int? Day6NActual { get; set; }
        public int? Day7DPlan { get; set; }
        public int? Day7DActual { get; set; }
        public int? Day7NPlan { get; set; }
        public int? Day7NActual { get; set; }
        public int? Day8DPlan { get; set; }
        public int? Day8DActual { get; set; }
        public int? Day8NPlan { get; set; }
        public int? Day8NActual { get; set; }
        public int? Day9DPlan { get; set; }
        public int? Day9DActual { get; set; }
        public int? Day9NPlan { get; set; }
        public int? Day9NActual { get; set; }
        public int? Day10DPlan { get; set; }
        public int? Day10DActual { get; set; }
        public int? Day10NPlan { get; set; }
        public int? Day10NActual { get; set; }
        public int? Day11DPlan { get; set; }
        public int? Day11DActual { get; set; }
        public int? Day11NPlan { get; set; }
        public int? Day11NActual { get; set; }
        public int? Day12DPlan { get; set; }
        public int? Day12DActual { get; set; }
        public int? Day12NPlan { get; set; }
        public int? Day12NActual { get; set; }
        public int? Day13DPlan { get; set; }
        public int? Day13DActual { get; set; }
        public int? Day13NPlan { get; set; }
        public int? Day13NActual { get; set; }
        public int? Day14DPlan { get; set; }
        public int? Day14DActual { get; set; }
        public int? Day14NPlan { get; set; }
        public int? Day14NActual { get; set; }
        public int? Day15DPlan { get; set; }
        public int? Day15DActual { get; set; }
        public int? Day15NPlan { get; set; }
        public int? Day15NActual { get; set; }
        public int? Day16DPlan { get; set; }
        public int? Day16DActual { get; set; }
        public int? Day16NPlan { get; set; }
        public int? Day16NActual { get; set; }
        public int? Day17DPlan { get; set; }
        public int? Day17DActual { get; set; }
        public int? Day17NPlan { get; set; }
        public int? Day17NActual { get; set; }
        public int? Day18DPlan { get; set; }
        public int? Day18DActual { get; set; }
        public int? Day18NPlan { get; set; }
        public int? Day18NActual { get; set; }
        public int? Day19DPlan { get; set; }
        public int? Day19DActual { get; set; }
        public int? Day19NPlan { get; set; }
        public int? Day19NActual { get; set; }
        public int? Day20DPlan { get; set; }
        public int? Day20DActual { get; set; }
        public int? Day20NPlan { get; set; }
        public int? Day20NActual { get; set; }
        public int? Day21DPlan { get; set; }
        public int? Day21DActual { get; set; }
        public int? Day21NPlan { get; set; }
        public int? Day21NActual { get; set; }
        public int? Day22DPlan { get; set; }
        public int? Day22DActual { get; set; }
        public int? Day22NPlan { get; set; }
        public int? Day22NActual { get; set; }
        public int? Day23DPlan { get; set; }
        public int? Day23DActual { get; set; }
        public int? Day23NPlan { get; set; }
        public int? Day23NActual { get; set; }
        public int? Day24DPlan { get; set; }
        public int? Day24DActual { get; set; }
        public int? Day24NPlan { get; set; }
        public int? Day24NActual { get; set; }
        public int? Day25DPlan { get; set; }
        public int? Day25DActual { get; set; }
        public int? Day25NPlan { get; set; }
        public int? Day25NActual { get; set; }
        public int? Day26DPlan { get; set; }
        public int? Day26DActual { get; set; }
        public int? Day26NPlan { get; set; }
        public int? Day26NActual { get; set; }
        public int? Day27DPlan { get; set; }
        public int? Day27DActual { get; set; }
        public int? Day27NPlan { get; set; }
        public int? Day27NActual { get; set; }
        public int? Day28DPlan { get; set; }
        public int? Day28DActual { get; set; }
        public int? Day28NPlan { get; set; }
        public int? Day28NActual { get; set; }
        public int? Day29DPlan { get; set; }
        public int? Day29DActual { get; set; }
        public int? Day29NPlan { get; set; }
        public int? Day29NActual { get; set; }
        public int? Day30DPlan { get; set; }
        public int? Day30DActual { get; set; }
        public int? Day30NPlan { get; set; }
        public int? Day30NActual { get; set; }
        public int? Day31DPlan { get; set; }
        public int? Day31DActual { get; set; }
        public int? Day31NPlan { get; set; }
        public int? Day31NActual { get; set; }
        public string? Problem1Topic { get; set; }
        public string? Problem1Cause { get; set; }
        public string? Problem1Resolve { get; set; }
        public string? Problem1Time { get; set; }
        public string? Problem2Topic { get; set; }
        public string? Problem2Cause { get; set; }
        public string? Problem2Resolve { get; set; }
        public string? Problem2Time { get; set; }
        public string? Problem3Topic { get; set; }
        public string? Problem3Cause { get; set; }
        public string? Problem3Resolve { get; set; }
        public string? Problem3Time { get; set; }
        public string? Problem4Topic { get; set; }
        public string? Problem4Cause { get; set; }
        public string? Problem4Resolve { get; set; }
        public string? Problem4Time { get; set; }
        public string? Problem5Topic { get; set; }
        public string? Problem5Cause { get; set; }
        public string? Problem5Resolve { get; set; }
        public string? Problem5Time { get; set; }
        public string? Remark1 { get; set; }
        public string? Remark2 { get; set; }
        public string? Remark3 { get; set; }
        public string? Remark4 { get; set; }
        public string? Remark5 { get; set; }
        public DateTime? UpdateDate { get; set; }
        public string? UpdateBy { get; set; }
        public string? CreateBy { get; set; }
        public DateTime? CreateDate { get; set; }
        public string? CommentD1 { get; set; }
        public string? CommentD2 { get; set; }
        public string? CommentD3 { get; set; }
        public string? CommentD4 { get; set; }
        public string? CommentD5 { get; set; }
        public string? CommentD6 { get; set; }
        public string? CommentD7 { get; set; }
        public string? CommentD8 { get; set; }
        public string? CommentD9 { get; set; }
        public string? CommentD10 { get; set; }
        public string? CommentD11 { get; set; }
        public string? CommentD12 { get; set; }
        public string? CommentD13 { get; set; }
        public string? CommentD14 { get; set; }
        public string? CommentD15 { get; set; }
        public string? CommentD16 { get; set; }
        public string? CommentD17 { get; set; }
        public string? CommentD18 { get; set; }
        public string? CommentD19 { get; set; }
        public string? CommentD20 { get; set; }
        public string? CommentD21 { get; set; }
        public string? CommentD22 { get; set; }
        public string? CommentD23 { get; set; }
        public string? CommentD24 { get; set; }
        public string? CommentD25 { get; set; }
        public string? CommentD26 { get; set; }
        public string? CommentD27 { get; set; }
        public string? CommentD28 { get; set; }
        public string? CommentD29 { get; set; }
        public string? CommentD30 { get; set; }
        public string? CommentD31 { get; set; }
    }
}
