using System;
using System.Collections.Generic;

namespace API_DCI_DIAGRAM_SVG.Models
{
    public partial class PtMstr
    {
        public string PtPart { get; set; } = null!;
        public string? PtDesc1 { get; set; }
        public string? PtDesc2 { get; set; }
        public string? PtUm { get; set; }
        public string? PtQad13 { get; set; }
        public double? PtQad12 { get; set; }
        public string? PtDraw { get; set; }
        public double? PtProdLine { get; set; }
        public string? PtGroup { get; set; }
        public string? PtPartType { get; set; }
        public string? PtStatus { get; set; }
        public string? PtAbc { get; set; }
        public string? PtIssPol { get; set; }
        public string? PtPhantom { get; set; }
        public string? PtLoc { get; set; }
        public double? PtQad01 { get; set; }
        public double? PtQad02 { get; set; }
        public double? PtAbcAmt { get; set; }
        public double? PtQad03 { get; set; }
        public double? PtQad04 { get; set; }
        public double? PtAvgInt { get; set; }
        public DateTime? PtQad05 { get; set; }
        public double? PtCycInt { get; set; }
        public string? PtQad06 { get; set; }
        public string? PtQad07 { get; set; }
        public string? PtQad08 { get; set; }
        public string? PtMs { get; set; }
        public string? PtPlanOrd { get; set; }
        public string? PtMrp { get; set; }
        public string? PtOrdPol { get; set; }
        public double? PtOrdQty { get; set; }
        public double? PtOrdPer { get; set; }
        public double? PtSftyStk { get; set; }
        public double? PtSftyTime { get; set; }
        public double? PtRop { get; set; }
        public string? PtBuyer { get; set; }
        public string? PtVend { get; set; }
        public double? PtQad09 { get; set; }
        public string? PtPmCode { get; set; }
        public double? PtMfgLead { get; set; }
        public double? PtPurLead { get; set; }
        public string? PtInspRqd { get; set; }
        public double? PtInspLead { get; set; }
        public double? PtCumLead { get; set; }
        public double? PtOrdMin { get; set; }
        public double? PtOrdMax { get; set; }
        public double? PtOrdMult { get; set; }
        public double? PtYieldPct { get; set; }
        public double? PtQad16 { get; set; }
        public double? PtSetup { get; set; }
        public double? PtSetupLl { get; set; }
        public double? PtRunLl { get; set; }
        public double? PtRun { get; set; }
        public double? PtPrice { get; set; }
        public double? PtXmtlTl { get; set; }
        public double? PtXlbrTl { get; set; }
        public double? PtXbdnTl { get; set; }
        public double? PtXsubTl { get; set; }
        public double? PtXmtlLl { get; set; }
        public double? PtXlbrLl { get; set; }
        public double? PtXbdnLl { get; set; }
        public double? PtXsubLl { get; set; }
        public double? PtXtotCur { get; set; }
        public DateTime? PtCurDate { get; set; }
        public double? PtXmtlStdtl { get; set; }
        public double? PtXlbrStdtl { get; set; }
        public double? PtXbdnStdtl { get; set; }
        public double? PtXsubStdtl { get; set; }
        public double? PtXtotStd { get; set; }
        public DateTime? PtStdDate { get; set; }
        public double? PtLlCode { get; set; }
        public double? PtAbcQty { get; set; }
        public double? PtQad10 { get; set; }
        public double? PtQad11 { get; set; }
        public string? PtRouting { get; set; }
        public string? PtLotSer { get; set; }
        public double? PtTimefence { get; set; }
        public double? PtXmtlStdll { get; set; }
        public double? PtXlbrStdll { get; set; }
        public double? PtXbdnStdll { get; set; }
        public double? PtXsubStdll { get; set; }
        public string? PtRev { get; set; }
        public string? PtLastEco { get; set; }
        public string? PtQad15 { get; set; }
        public string? PtQad17 { get; set; }
        public double? PtQcLead { get; set; }
        public string? PtAutoLot { get; set; }
        public double? PtAssay { get; set; }
        public double? PtBatch { get; set; }
        public string? PtQad14 { get; set; }
        public string? PtUser3 { get; set; }
        public string? PtUser1 { get; set; }
        public string? PtUser2 { get; set; }
        public double? PtNetWt { get; set; }
        public string? PtNetWtUm { get; set; }
        public double? PtSize { get; set; }
        public string? PtSizeUm { get; set; }
        public string? PtTaxable { get; set; }
        public double? PtTaxc { get; set; }
        public string? PtRollup { get; set; }
        public double? PtXovhLl { get; set; }
        public double? PtXovhTl { get; set; }
        public double? PtXovhStdll { get; set; }
        public double? PtXovhStdtl { get; set; }
        public double? PtSite { get; set; }
        public double? PtShelflife { get; set; }
        public string? PtCritical { get; set; }
        public string? PtSnglLot { get; set; }
        public string? PtUpc { get; set; }
        public string? PtHazard { get; set; }
        public DateTime? PtAdded { get; set; }
        public string? PtChr01 { get; set; }
        public string? PtChr02 { get; set; }
        public string? PtChr03 { get; set; }
        public string? PtChr04 { get; set; }
        public string? PtChr05 { get; set; }
        public string? PtChr06 { get; set; }
        public string? PtChr07 { get; set; }
        public string? PtChr08 { get; set; }
        public string? PtChr09 { get; set; }
        public string? PtChr10 { get; set; }
        public string? PtDte01 { get; set; }
        public string? PtDte02 { get; set; }
        public double? PtDec01 { get; set; }
        public double? PtDec02 { get; set; }
        public string? PtLog01 { get; set; }
        public string? PtLog02 { get; set; }
        public double? PtQad18 { get; set; }
        public double? PtQad21 { get; set; }
        public double? PtQad19 { get; set; }
        public double? PtQad20 { get; set; }
        public double? PtLength { get; set; }
        public double? PtHeight { get; set; }
        public double? PtWidth { get; set; }
        public string? PtDimUm { get; set; }
        public string? PtPkgCode { get; set; }
        public string? PtNetwork { get; set; }
        public double? PtLlDrp { get; set; }
        public string? PtFrClass { get; set; }
        public string? PtSpecHdlg { get; set; }
        public string? PtBomCode { get; set; }
        public string? PtLocType { get; set; }
        public string? PtTranstype { get; set; }
        public string? PtCover { get; set; }
        public string? PtUnitIsb { get; set; }
        public string? PtArticle { get; set; }
        public double? PtPoSite { get; set; }
        public double? PtShipWt { get; set; }
        public string? PtShipWtUm { get; set; }
        public string? PtFormula { get; set; }
        public string? PtDea { get; set; }
        public string? PtQad26 { get; set; }
        public string? PtQad22 { get; set; }
        public double? PtQad25 { get; set; }
        public double? PtQad24 { get; set; }
        public double? PtQad23 { get; set; }
        public string? PtCommCode { get; set; }
        public string? PtInstCall { get; set; }
        public string? PtSysType { get; set; }
        public string? PtTariff { get; set; }
        public string? PtOrigin { get; set; }
        public double? PtSttr { get; set; }
        public double? PtMfgMtbf { get; set; }
        public double? PtMfgMttr { get; set; }
        public string? PtFru { get; set; }
        public string? PtVenWarr { get; set; }
        public string? PtSvcGroup { get; set; }
        public string? PtSvcType { get; set; }
        public double? PtMtbf { get; set; }
        public double? PtMttr { get; set; }
        public string? PtIsb { get; set; }
        public double? PtPvmDays { get; set; }
        public string? PtWarrCd { get; set; }
        public DateTime? PtModDate { get; set; }
        public string? PtUserid { get; set; }
        public string? PtObsDate { get; set; }
        public string? PtPvmBom { get; set; }
        public string? PtPvmRoute { get; set; }
        public string? PtPvmUm { get; set; }
        public string? PtRpBom { get; set; }
        public string? PtRpRoute { get; set; }
        public string? PtRpVendor { get; set; }
        public string? PtRctpoStatus { get; set; }
        public string? PtRollupId { get; set; }
        public double? PtSpecGrav { get; set; }
        public string? PtJointType { get; set; }
        public double? PtMfgPct { get; set; }
        public double? PtPurPct { get; set; }
        public double? PtDrpPct { get; set; }
        public string? PtPouCode { get; set; }
        public double? PtWksAvg { get; set; }
        public double? PtWksMax { get; set; }
        public double? PtWksMin { get; set; }
        public double? PtPickLogic { get; set; }
        public string? PtFiscalClass { get; set; }
        public string? PtDsgnGrp { get; set; }
        public string? PtDrwgLoc { get; set; }
        public string? PtEcnRev { get; set; }
        public string? PtDrwgSize { get; set; }
        public string? PtModel { get; set; }
        public string? PtRepairable { get; set; }
        public string? PtRctwoStatus { get; set; }
        public string? PtLotGrp { get; set; }
        public string? PtRctpoActive { get; set; }
        public string? PtRctwoActive { get; set; }
        public string? PtBreakCat { get; set; }
        public string? PtFscCode { get; set; }
        public string? PtTraceActive { get; set; }
        public string? PtTraceDetail { get; set; }
        public string? PtPmMrp { get; set; }
        public string? PtInsCallType { get; set; }
        public string? PtInsBom { get; set; }
        public string? PtInsRoute { get; set; }
        public string? PtPromo { get; set; }
        public double? PtMeterInterval { get; set; }
        public string? PtMeterUm { get; set; }
        public string? PtWh { get; set; }
        public double? PtBtbType { get; set; }
        public string? PtCfgType { get; set; }
        public string? PtAppOwner { get; set; }
        public string? PtOpYield { get; set; }
        public string? PtRunSeq1 { get; set; }
        public string? PtRunSeq2 { get; set; }
        public double? PtAtpEnforcement { get; set; }
        public string? PtAtpFamily { get; set; }
        public string? PtDomain { get; set; }
        public double? OidPtMstr { get; set; }
        public decimal? MinStock { get; set; }
        public decimal? MaxStock { get; set; }
        public decimal? SafetyStock { get; set; }
        public string? ShipTo { get; set; }
        public string? ReceiveLocation { get; set; }
        public decimal? SafetyOrder { get; set; }
        public decimal? WipRatio { get; set; }
        public string? VdMulti { get; set; }
    }
}
