using System;
using System.Collections.Generic;

namespace API_DCI_DIAGRAM_SVG.Models
{
    public partial class Pu1ExplosionPurchasing
    {
        public long Id { get; set; }
        public string? GenPurchaseCode { get; set; }
        public string? LocalCode { get; set; }
        public string? ImportCode { get; set; }
        public string? ModelCode { get; set; }
        public string? Model { get; set; }
        public string? PtParent { get; set; }
        public string? PtPart { get; set; }
        public decimal? BomQty { get; set; }
        public string? BomUm { get; set; }
        public decimal? StockQty { get; set; }
        public decimal? WipQty { get; set; }
        public decimal? PoBalanceQty { get; set; }
        public decimal? CurrPoQty { get; set; }
        public decimal? FutrPoQty { get; set; }
        public decimal? RemainedPlan { get; set; }
        public decimal? Month1St { get; set; }
        public string? Month1StCode { get; set; }
        public decimal? Month1StPlanBom { get; set; }
        public decimal? Month1Nd { get; set; }
        public string? Month1NdCode { get; set; }
        public decimal? Month1NdPlanBom { get; set; }
        public decimal? Month2St { get; set; }
        public string? Month2StCode { get; set; }
        public decimal? Month2StPlanBom { get; set; }
        public decimal? Month2Nd { get; set; }
        public string? Month2NdCode { get; set; }
        public decimal? Month2NdPlanBom { get; set; }
        public decimal? Month3St { get; set; }
        public string? Month3StCode { get; set; }
        public decimal? Month3StPlanBom { get; set; }
        public decimal? Month3Nd { get; set; }
        public string? Month3NdCode { get; set; }
        public decimal? Month3NdPlanBom { get; set; }
        public decimal? Month4St { get; set; }
        public string? Month4StCode { get; set; }
        public decimal? Month4StPlanBom { get; set; }
        public decimal? Month4Nd { get; set; }
        public string? Month4NdCode { get; set; }
        public decimal? Month4NdPlanBom { get; set; }
        public decimal? Month5St { get; set; }
        public string? Month5StCode { get; set; }
        public decimal? Month5StPlanBom { get; set; }
        public decimal? Month5Nd { get; set; }
        public string? Month5NdCode { get; set; }
        public decimal? Month5NdPlanBom { get; set; }
        public decimal? Month6St { get; set; }
        public string? Month6StCode { get; set; }
        public decimal? Month6StPlanBom { get; set; }
        public decimal? Month6Nd { get; set; }
        public string? Month6NdCode { get; set; }
        public decimal? Month6NdPlanBom { get; set; }
        public decimal? Month7St { get; set; }
        public string? Month7StCode { get; set; }
        public decimal? Month7StPlanBom { get; set; }
        public decimal? Month7Nd { get; set; }
        public string? Month7NdCode { get; set; }
        public decimal? Month7NdPlanBom { get; set; }
        public decimal? Month8St { get; set; }
        public string? Month8StCode { get; set; }
        public decimal? Month8StPlanBom { get; set; }
        public decimal? Month8Nd { get; set; }
        public string? Month8NdCode { get; set; }
        public decimal? Month8NdPlanBom { get; set; }
        public decimal? Month9St { get; set; }
        public string? Month9StCode { get; set; }
        public decimal? Month9StPlanBom { get; set; }
        public decimal? Month9Nd { get; set; }
        public string? Month9NdCode { get; set; }
        public decimal? Month9NdPlanBom { get; set; }
        public decimal? Month10St { get; set; }
        public string? Month10StCode { get; set; }
        public decimal? Month10StPlanBom { get; set; }
        public decimal? Month10Nd { get; set; }
        public string? Month10NdCode { get; set; }
        public decimal? Month10NdPlanBom { get; set; }
        public decimal? Month11St { get; set; }
        public string? Month11StCode { get; set; }
        public decimal? Month11StPlanBom { get; set; }
        public decimal? Month11Nd { get; set; }
        public string? Month11NdCode { get; set; }
        public decimal? Month11NdPlanBom { get; set; }
        public decimal? Month12St { get; set; }
        public string? Month12StCode { get; set; }
        public decimal? Month12StPlanBom { get; set; }
        public decimal? Month12Nd { get; set; }
        public string? Month12NdCode { get; set; }
        public decimal? Month12NdPlanBom { get; set; }
        public string? Status { get; set; }
        public string? CreateBy { get; set; }
        public DateTime? CreateDate { get; set; }
        public string? UpdateBy { get; set; }
        public DateTime? UpdateDate { get; set; }
    }
}
