using System;
using System.Collections.Generic;

namespace API_DCI_DIAGRAM_SVG.Models
{
    public partial class Pu4CalculatePurchasing
    {
        public long Id { get; set; }
        public string? GenPurchaseCode { get; set; }
        public string? LocalCode { get; set; }
        public string? ImportCode { get; set; }
        public string? OrderType { get; set; }
        public decimal? OrderLeadTime { get; set; }
        public bool? IsBoi { get; set; }
        public string? VdAddr { get; set; }
        public decimal? VdOrderRatio { get; set; }
        public string? PtPart { get; set; }
        public string? BomUm { get; set; }
        public decimal? StockQty { get; set; }
        public decimal? WipQty { get; set; }
        public decimal? PoBalanceQty { get; set; }
        public decimal? CurrPoQty { get; set; }
        public decimal? FutrPoQty { get; set; }
        public decimal? PackStdQty { get; set; }
        public decimal? SafetyRatio { get; set; }
        public decimal? RemainedPlan { get; set; }
        public decimal? Month1St { get; set; }
        public decimal? Month1StPrice { get; set; }
        public string? Month1StPriceCode { get; set; }
        public decimal? Month1StVendorQty { get; set; }
        public decimal? Month1StSurplusPackQty { get; set; }
        public string? Month1StCode { get; set; }
        public decimal? Month1Nd { get; set; }
        public decimal? Month1NdPrice { get; set; }
        public string? Month1NdPriceCode { get; set; }
        public decimal? Month1NdVendorQty { get; set; }
        public decimal? Month1NdSurplusPackQty { get; set; }
        public string? Month1NdCode { get; set; }
        public decimal? Month2St { get; set; }
        public decimal? Month2StPrice { get; set; }
        public string? Month2StPriceCode { get; set; }
        public decimal? Month3StVendorQty { get; set; }
        public decimal? Month2StVendorQty { get; set; }
        public decimal? Month2StSurplusPackQty { get; set; }
        public string? Month2StCode { get; set; }
        public decimal? Month2Nd { get; set; }
        public decimal? Month2NdPrice { get; set; }
        public string? Month2NdPriceCode { get; set; }
        public decimal? Month2NdVendorQty { get; set; }
        public decimal? Month2NdSurplusPackQty { get; set; }
        public string? Month2NdCode { get; set; }
        public decimal? Month3St { get; set; }
        public decimal? Month3StPrice { get; set; }
        public string? Month3StPriceCode { get; set; }
        public decimal? Month3StSurplusPackQty { get; set; }
        public string? Month3StCode { get; set; }
        public decimal? Month3Nd { get; set; }
        public decimal? Month3NdPrice { get; set; }
        public string? Month3NdPriceCode { get; set; }
        public decimal? Month3NdVendorQty { get; set; }
        public decimal? Month3NdSurplusPackQty { get; set; }
        public string? Month3NdCode { get; set; }
        public decimal? Month4St { get; set; }
        public decimal? Month4StPrice { get; set; }
        public string? Month4StPriceCode { get; set; }
        public decimal? Month4StVendorQty { get; set; }
        public decimal? Month4StSurplusPackQty { get; set; }
        public string? Month4StCode { get; set; }
        public decimal? Month4Nd { get; set; }
        public decimal? Month4NdPrice { get; set; }
        public string? Month4NdPriceCode { get; set; }
        public decimal? Month4NdVendorQty { get; set; }
        public decimal? Month4NdSurplusPackQty { get; set; }
        public string? Month4NdCode { get; set; }
        public decimal? Month5St { get; set; }
        public decimal? Month5StPrice { get; set; }
        public string? Month5StPriceCode { get; set; }
        public decimal? Month5StVendorQty { get; set; }
        public decimal? Month5StSurplusPackQty { get; set; }
        public string? Month5StCode { get; set; }
        public decimal? Month5Nd { get; set; }
        public decimal? Month5NdPrice { get; set; }
        public string? Month5NdPriceCode { get; set; }
        public decimal? Month5NdVendorQty { get; set; }
        public decimal? Month5NdSurplusPackQty { get; set; }
        public string? Month5NdCode { get; set; }
        public decimal? Month6St { get; set; }
        public decimal? Month6StPrice { get; set; }
        public string? Month6StPriceCode { get; set; }
        public decimal? Month6StVendorQty { get; set; }
        public decimal? Month6StSurplusPackQty { get; set; }
        public string? Month6StCode { get; set; }
        public decimal? Month6Nd { get; set; }
        public decimal? Month6NdPrice { get; set; }
        public string? Month6NdPriceCode { get; set; }
        public decimal? Month6NdVendorQty { get; set; }
        public decimal? Month6NdSurplusPackQty { get; set; }
        public string? Month6NdCode { get; set; }
        public decimal? Month7St { get; set; }
        public decimal? Month7StPrice { get; set; }
        public string? Month7StPriceCode { get; set; }
        public decimal? Month7StVendorQty { get; set; }
        public decimal? Month7StSurplusPackQty { get; set; }
        public string? Month7StCode { get; set; }
        public decimal? Month7Nd { get; set; }
        public decimal? Month7NdPrice { get; set; }
        public string? Month7NdPriceCode { get; set; }
        public decimal? Month7NdVendorQty { get; set; }
        public decimal? Month7NdSurplusPackQty { get; set; }
        public string? Month7NdCode { get; set; }
        public decimal? Month8St { get; set; }
        public decimal? Month8StPrice { get; set; }
        public string? Month8StPriceCode { get; set; }
        public decimal? Month8StVendorQty { get; set; }
        public decimal? Month8StSurplusPackQty { get; set; }
        public string? Month8StCode { get; set; }
        public decimal? Month8Nd { get; set; }
        public decimal? Month8NdPrice { get; set; }
        public string? Month8NdPriceCode { get; set; }
        public decimal? Month8NdVendorQty { get; set; }
        public decimal? Month8NdSurplusPackQty { get; set; }
        public string? Month8NdCode { get; set; }
        public decimal? Month9St { get; set; }
        public decimal? Month9StPrice { get; set; }
        public string? Month9StPriceCode { get; set; }
        public decimal? Month9StVendorQty { get; set; }
        public decimal? Month9StSurplusPackQty { get; set; }
        public string? Month9StCode { get; set; }
        public decimal? Month9Nd { get; set; }
        public decimal? Month9NdPrice { get; set; }
        public string? Month9NdPriceCode { get; set; }
        public decimal? Month9NdVendorQty { get; set; }
        public decimal? Month9NdSurplusPackQty { get; set; }
        public string? Month9NdCode { get; set; }
        public decimal? Month10St { get; set; }
        public decimal? Month10StPrice { get; set; }
        public string? Month10StPriceCode { get; set; }
        public decimal? Month10StVendorQty { get; set; }
        public decimal? Month10StSurplusPackQty { get; set; }
        public string? Month10StCode { get; set; }
        public decimal? Month10Nd { get; set; }
        public decimal? Month10NdPrice { get; set; }
        public string? Month10NdPriceCode { get; set; }
        public decimal? Month10NdVendorQty { get; set; }
        public decimal? Month10NdSurplusPackQty { get; set; }
        public string? Month10NdCode { get; set; }
        public decimal? Month11St { get; set; }
        public decimal? Month11StPrice { get; set; }
        public string? Month11StPriceCode { get; set; }
        public decimal? Month11StVendorQty { get; set; }
        public decimal? Month11StSurplusPackQty { get; set; }
        public string? Month11StCode { get; set; }
        public decimal? Month11Nd { get; set; }
        public decimal? Month11NdPrice { get; set; }
        public string? Month11NdPriceCode { get; set; }
        public decimal? Month11NdVendorQty { get; set; }
        public decimal? Month11NdSurplusPackQty { get; set; }
        public string? Month11NdCode { get; set; }
        public decimal? Month12St { get; set; }
        public decimal? Month12StPrice { get; set; }
        public string? Month12StPriceCode { get; set; }
        public decimal? Month12StVendorQty { get; set; }
        public decimal? Month12StSurplusPackQty { get; set; }
        public string? Month12StCode { get; set; }
        public decimal? Month12Nd { get; set; }
        public decimal? Month12NdPrice { get; set; }
        public string? Month12NdPriceCode { get; set; }
        public decimal? Month12NdVendorQty { get; set; }
        public decimal? Month12NdSurplusPackQty { get; set; }
        public string? Month12NdCode { get; set; }
        public string? Status { get; set; }
        public string? CreateBy { get; set; }
        public DateTime? CreateDate { get; set; }
        public string? UpdateBy { get; set; }
        public DateTime? UpdateDate { get; set; }
    }
}
